language: ruby
cache: bundler
dist: trusty
rvm:
  - ruby-2.0
  - ruby-2.1
  - ruby-2.2
  - ruby-2.3
  - ruby-2.4
  - rbx
  - jruby
before_install:
  - gem update --system
  - gem update bundler
before_script:
  - bundle exec rubocop -D
notifications:
  email:
    on_success: change
    on_failure: change
